---
abstract: ~
author:
  - 'Takatoshi Kitano <kitano.tk@gmail.com>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.720'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Devel-DLMProf
no_index:
  directory:
    - inc
    - t
requires:
  Linux::Smaps: 0
  Path::Class: 0
version: 0.03_01
